---
title: "main"
author: "Ashley Blawas"
date: '2024-06-13'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries include=FALSE}
library(tidyverse)
library(readxl)
library(stringr)
library(dplyr)

# Set home for figures
fig_path = "C:/Users/ashle/Dropbox/Ashley/Post-Doc/Projects/DQO preconditioning/figs"

```

```{r  include=FALSE}

# Where does data live?
data_path = "C:/Users/ashle/Dropbox/Ashley/Post-Doc/Projects/DQO preconditioning/data"

# What is the file name?
file_name = "10364_Supplemental_Data_061224.xlsx"

# What are the sheet names
sheet1 = "S1. Unenriched Metadata"
sheet2 = "S2. Uneriched Abundances" # NP = # of precursors, PGQ = protein group quantity
sheet3 = "S3. Phos Metadata"
sheet4 = "S4. Phos localized" # Place where it was on the protein
sheet5 = "S5. Phos not localized" # Not able to place where it was on the protein
sheet6 = "S6. Phos filtered" # 


```

## Load in the metadata
```{r}
# Load in the Unenriched Metadata
unenriched_metadata <- read_excel(paste0(data_path, "/", file_name), sheet = sheet1)

# Make the Animal IDs for the controls unique
n_na = sum(is.na(unenriched_metadata$Condition))
unenriched_metadata$Condition[is.na(unenriched_metadata$Condition)] <- paste0("NA_VALUE_", seq_len(n_na))

# Load in the Phosphorylation Metadata - had to add an "h" to one of the "tech" in phos metadata
phos_metadata <- read_excel(paste0(data_path, "/", file_name), sheet = sheet3)

# Make the Animal IDs for the controls unique
n_na = sum(phos_metadata$Replicate == "SPQC_prep")
phos_metadata$Replicate[phos_metadata$Replicate == "SPQC_prep"] <- paste0("SPQC_prep", seq_len(n_na))

n_na = sum(phos_metadata$Replicate == "SPQC_tech")
phos_metadata$Replicate[phos_metadata$Replicate == "SPQC_tech"] <- paste0("SPQC_tech", seq_len(n_na))
```

## Load in the unenriched dataset
```{r}
# Load in the Unenriched Metadata
unenriched_abundances <- read_excel(paste0(data_path, "/", file_name), sheet = sheet2)

for (i in 1:nrow(unenriched_metadata)){
  curr_name = names(unenriched_abundances)[i+3] 
  curr_id = unlist(str_extract_all(curr_name, "ID.+htrms"))
  
  temp_metadata = unenriched_metadata %>%
  filter(str_detect(`File Name`, curr_id))
  
  curr_animal = temp_metadata$Animal
  curr_condition = temp_metadata$Condition
  
  unenriched_abundances <- unenriched_abundances %>% rename(!! paste0(curr_animal, "_", curr_condition, "_", "NP") := curr_name)
  
}


for (i in 1:nrow(unenriched_metadata)){
  curr_name = names(unenriched_abundances)[i+36] 
  curr_id = unlist(str_extract_all(curr_name, "ID.+htrms"))
  
  temp_metadata = unenriched_metadata %>%
  filter(str_detect(`File Name`, curr_id))
  
  curr_animal = temp_metadata$Animal
  curr_condition = temp_metadata$Condition
  
  unenriched_abundances <- unenriched_abundances %>% rename(!! paste0(curr_animal, "_", curr_condition, "_", "PGQ") := curr_name)
  
}

```

## PCA of unenriched abundances
```{r}

# Step 1: Make one column (e.g., 'ID') the new header
new_header <- unenriched_abundances$PG.ProteinNames # Take the values of the 'ID' column
unenriched_abundances_t <- unenriched_abundances[, -c(1, 2, 3)]  # Remove the 'ID' column from the original data frame

# Select only columns that contain "PGQ" in the name
unenriched_abundances_t <- unenriched_abundances_t[, grep("PGQ", colnames(unenriched_abundances_t))]

# Step 2: Transpose the data frame
unenriched_abundances_t <- t(unenriched_abundances_t)

# Step 3: Set the new header
colnames(unenriched_abundances_t) <- new_header

# Step 4: Convert the transposed matrix back to a data frame & to numeric entries
unenriched_abundances_t <- as.data.frame(unenriched_abundances_t)
unenriched_abundances_t[] <- lapply(unenriched_abundances_t, as.numeric)

# Step 5: Impute NaNs with column medians
# Impute with column medians
unenriched_abundances_t <- unenriched_abundances_t
for (i in 1:ncol(unenriched_abundances_t)) {
  unenriched_abundances_t[is.na(unenriched_abundances_t[, i]), i] <- 0
}

# Step 6: Run PCA on the numeric abundance data
pca_result <- prcomp(unenriched_abundances_t, scale. = TRUE)

# Step 7: Check the summary of PCA result to view the variance explained by each principal component
#summary(pca_result)

# Step 8: Visualize the first two principal components in a biplot
# This plot shows how each sample (row) is positioned based on the first two principal components
#biplot(pca_result)

# Step 9: Create a PCA plot with points colored by the Protein Group if available
# First, add the PG.ProteinGroups as a factor variable to the PCA results
pca_df <- data.frame(pca_result$x)  # Extract the PCA scores for the samples

# Extract the rownames and add them as a variable to the PCA output
row_names <- rownames(unenriched_abundances_t)
pca_df <- pca_df %>%
  mutate(animal = str_extract(row_names, "^[^0-9]*")) %>%
  mutate(animalday = sub("([^_]+).*", "\\1", row_names)) %>%
  mutate(trialtype = str_extract(row_names, "^[^_]+_([^_]+)")) %>%
  mutate(trialtype = sub("^[^_]+_", "", trialtype)) %>%
  filter(trialtype != "PC6B")

# Filter out rows where 'group' contains 'lono'
pca_df <- pca_df %>% filter(!grepl("lono", animal))

# Add in animal codes
pca_df$animal <- gsub("hoku", "63H4", pca_df$animal)
pca_df$animal <- gsub("kolohe", "6JK5", pca_df$animal)
pca_df$animal <- gsub("liho", "01L5", pca_df$animal)
pca_df$animal <- gsub("nainoa", "9ON6", pca_df$animal)

# Replace weird codes for QC
pca_df$trialtype <- gsub("NA", "QC", pca_df$trialtype)

# Now, use ggplot2 for a more customized PCA plot
ggplot(pca_df, aes(x = PC1, y = PC2, color = animal, shape = trialtype)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "PCA of Protein Abundance Data", x = "PC1", y = "PC2") +
  scale_color_manual(values = c('63H4' = '#CC6677',
                                #'hoku231019' = '#CC6699',
                                '6JK5' = '#DDCC77',
                                #'kolohe231016' = '#DDCC22',
                                '01L5' = '#117733',
                                #'liho231018' = '#116655',
                                #'lono231009' = '#6699CC',
                                #'lono231016' = '#6688CC',
                                '9ON6' = '#EE8866',
                                #'nainoa231016' = '#EE8888',
                                'SPQC' = 'black'), name = "Animal") +  
    scale_shape_manual(values = c(15, 16, 17, 0, 1, 2, 3, 4, 5, 6), name = "Trial Type") +  # Manually assign the shapes
  theme_minimal() +
   geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1) +  # Dotted horizontal line at y = 0
  geom_vline(xintercept = 0, linetype = "dotted", color = "black", size = 1) + 
  theme(
    # Adding black box around the plot
    #plot.background = element_rect(color = "black", fill = NA, size = 1), # border size and color
    panel.border = element_rect(color = "black", fill = NA, size = 1), # border around the plot area (panel)
    legend.spacing = unit(0.05, "lines"),  # Adjust spacing between legend entries
    legend.key.size = unit(0.4, "cm"),   # Adjust the size of the legend key
    legend.title = element_text(size = 10), # Adjust the legend title size
    legend.text = element_text(size = 8)   # Adjust the legend text size
  )

filename <- "PCA_unenrichedabundances"
  
 # Save the plot (for example, as a PNG)
ggsave(paste0(fig_path, "/", filename, ".png"), units="in", width = 5, height = 3, dpi = 600, bg = "white")
cat(paste("File", filename, "has been saved.\n"))

```

## Load in the filtered phosphoprotein dataset
```{r}
# Load in the Unenriched Metadata
phos_filtered <- read_excel(paste0(data_path, "/", file_name), sheet = sheet6)

# Drop CV columns
phos_filtered <- phos_filtered %>% dplyr::select(!starts_with("CV"))

# Change data frame organization to have names
for (i in 1:nrow(phos_metadata)){
  curr_name = names(phos_filtered)[i+5] # Add 5 because there are 5 columns that are not IDs
  curr_id = unlist(str_extract_all(curr_name, "ID.+htrms"))
  
  temp_metadata = phos_metadata %>%
  filter(str_detect(`File Name`, curr_id))
  
  curr_animal = temp_metadata$Condition
  curr_condition = temp_metadata$Replicate
  
  phos_filtered <- phos_filtered %>% rename(!! paste0(curr_animal, "_", curr_condition, "_", "EG") := curr_name)
  
}

```


# Make data frame for plotting

```{r}

phos_filtered <- phos_filtered %>% select(-PG.ProteinAccessions, -PG.ProteinDescriptions, -PG.ProteinNames, -EG.PrecursorId)

phos_filtered <- phos_filtered %>% pivot_longer(!PG.Genes, names_to = "Sample") %>%
  rename(Value = value) %>% 
  rename(Gene = PG.Genes)

# Mutate new columns
phos_filtered <- phos_filtered %>% mutate(Animal = str_extract(Sample, "^\\D+")) %>%
  mutate(Date = str_extract(Sample, "\\d+")) %>%
  mutate(Condition = sub("^[^_]*_([^_]*).*", "\\1", Sample)) %>%
  dplyr::select(-Sample) %>%
  dplyr::select(Gene, Animal, Condition, Date, Value)
  

```

## PCA of phosphoenriched abundances
```{r}

# Step 1: Make one column (e.g., 'ID') the new header
new_header <- phos_filtered$PG.ProteinAccessions # Take the values of the 'ID' column
phos_filtered_t <- phos_filtered[, -c(1, 2, 3, 4, 5)]  # Remove the 'ID' column from the original data frame

# Step 2: Transpose the data frame
phos_filtered_t <- t(phos_filtered_t)

# Step 3: Set the new header
colnames(phos_filtered_t) <- new_header

# Step 4: Convert the transposed matrix back to a data frame & to numeric entries
phos_filtered_t <- as.data.frame(phos_filtered_t)
phos_filtered_t[] <- lapply(phos_filtered_t, as.numeric)

# Step 5: Impute NaNs with column medians
# Impute with column medians
phos_filtered_t <- phos_filtered_t
for (i in 1:ncol(phos_filtered_t)) {
  phos_filtered_t[is.na(phos_filtered_t[, i]), i] <- 0
}

# Step 6: Run PCA on the numeric abundance data
pca_result <- prcomp(phos_filtered_t, scale. = TRUE)

# Step 7: Check the summary of PCA result to view the variance explained by each principal component
#summary(pca_result)

# Step 8: Visualize the first two principal components in a biplot
# This plot shows how each sample (row) is positioned based on the first two principal components
#biplot(pca_result)

# Step 9: Create a PCA plot with points colored by the Protein Group if available
# First, add the PG.ProteinGroups as a factor variable to the PCA results
pca_df <- data.frame(pca_result$x)  # Extract the PCA scores for the samples

# Extract the rownames and add them as a variable to the PCA output
row_names <- rownames(phos_filtered_t)
pca_df <- pca_df %>%
  mutate(animal = str_extract(row_names, "^[^0-9]*")) %>%
  mutate(animalday = sub("([^_]+).*", "\\1", row_names)) %>%
  mutate(trialtype = str_extract(row_names, "^[^_]+_([^_]+)")) %>%
  mutate(trialtype = sub("^[^_]+_", "", trialtype))%>%
  filter(trialtype != "PC6B")

# Filter out rows where 'group' contains 'lono'
pca_df <- pca_df %>% filter(!grepl("lono", animal))

# Add in animal codes
pca_df$animal <- gsub("hoku", "63H4", pca_df$animal)
pca_df$animal <- gsub("kolohe", "6JK5", pca_df$animal)
pca_df$animal <- gsub("liho", "01L5", pca_df$animal)
pca_df$animal <- gsub("nainoa", "9ON6", pca_df$animal)

# Replace weird codes for QC
pca_df$trialtype <- gsub("prep", "QC1", pca_df$trialtype)
pca_df$trialtype <- gsub("tech", "QC2", pca_df$trialtype)


# Now, use ggplot2 for a more customized PCA plot
ggplot(pca_df, aes(x = PC1, y = PC2, color = animal, shape = trialtype)) +
  geom_point(size = 3, alpha = 0.8) +
  labs(title = "PCA of Phospho-Enriched Data", x = "PC1", y = "PC2") +
  scale_color_manual(values = c('63H4' = '#CC6677',
                                #'hoku231019' = '#CC6699',
                                '6JK5' = '#DDCC77',
                                #'kolohe231016' = '#DDCC22',
                                '01L5' = '#117733',
                                #'liho231018' = '#116655',
                                #'lono231009' = '#6699CC',
                                #'lono231016' = '#6688CC',
                                '9ON6' = '#EE8866',
                                #'nainoa231016' = '#EE8888',
                                'SPQC' = 'black'), name = "Animal") +  
  scale_shape_manual(values = c(15, 16, 17, 0, 1, 2, 3, 4, 5, 6), name = "Trial Type") +  # Manually assign the shapes
  theme_minimal() +
   geom_hline(yintercept = 0, linetype = "dotted", color = "black", size = 1) +  # Dotted horizontal line at y = 0
  geom_vline(xintercept = 0, linetype = "dotted", color = "black", size = 1) + 
  theme(
    # Adding black box around the plot
    #plot.background = element_rect(color = "black", fill = NA, size = 1), # border size and color
    
    panel.border = element_rect(color = "black", fill = NA, size = 1), # border around the plot area (panel)
    legend.spacing = unit(0.05, "lines"),  # Adjust spacing between legend entries
    legend.key.size = unit(0.4, "cm"),   # Adjust the size of the legend key
    legend.title = element_text(size = 10), # Adjust the legend title size
    legend.text = element_text(size = 8)   # Adjust the legend text size
  )

filename <- "PCA_phosphoenriched"
  
 # Save the plot (for example, as a PNG)
ggsave(paste0(fig_path, "/", filename, ".png"), units="in", width = 5, height = 3, dpi = 600, bg = "white")
cat(paste("File", filename, "has been saved.\n"))

```

# Choose a gene to test
```{r}

phos_filtered %>% filter(Gene == "HBA") %>%
  group_by(Animal, Condition) %>%
  summarize(MaxValue = max(Value)) %>%
  ungroup() %>%
  ggplot(aes(x=Condition, y = MaxValue)) +
  facet_wrap(vars(Animal), scales = "free") +
  geom_point()

```

# Look at change between time point A & C and C & D
```{r}

upup <- phos_filtered %>% 
  group_by(Gene, Animal) %>%
  if
```